In [9]:
import sqlite3
donnees = (
    {"id" : 0, "source" : "masource1", "start_t" : 0.0, "end_t" : 1.0, "p_ratio" : 0.5},
    {"id" : 1, "source" : "masource2", "start_t" : 1.0, "end_t" : 2.0, "p_ratio" : 0.5},
    {"id" : 2, "source" : "masource3", "start_t" : 2.0, "end_t" : 3.0, "p_ratio" : 0.5}
)

connexion = sqlite3.connect("tmp/database1.db")

curseur = connexion.cursor()
curseur.execute('''DROP TABLE chunks''')
curseur.execute('''CREATE TABLE chunks(
    id INTEGER PRIMARY KEY UNIQUE,
    source TEXT,
    start_t REAL,
    end_t REAL,
    p_ratio REAL
)''')

curseur.executemany("INSERT INTO chunks (id, source, start_t, end_t, p_ratio) VALUES (:id, :source, :start_t, :end_t, :p_ratio)", donnees)

connexion.commit()

l =curseur.execute("SELECT * FROM chunks")
print(list(map(lambda x: x[0], curseur.description)))
print([description[0] for description in curseur.description])    
for item in l:
    print(item)
    
n = curseur.execute('SELECT COUNT(*) FROM CHUNKS')    

print('COUNT =', curseur.fetchone()[0])

curseur.execute("SELECT * FROM chunks where id = ?", (1,))
rows = curseur.fetchall()
for row in rows:
    print(row)

curseur.execute("SELECT * FROM chunks where source = ?", ('masource1',))
rows = curseur.fetchall()
for row in rows:
    print(row)

#print(connexion.row_factory)
#c = connexion.cursor()
#c.execute("SELECT * FROM chunks")
#rows = c.fetchall()
#ids = [dict(rows)[x] for x in ('name',)]
#for id in ids:
#    print(id)

    

c = connexion.cursor()
c.execute("PRAGMA synchronous")
print("SYNCHRONOUS:", c.fetchone())
c.execute("PRAGMA journal_mode")
print("JOURNAL:", c.fetchone())
#c.execute("PRAGMA synchronous = OFF")
#c.execute("PRAGMA journal_mode = MEMORY")
    

c = connexion.cursor()
c.execute("PRAGMA optimize(1)")

connexion.close()

['id', 'source', 'start_t', 'end_t', 'p_ratio']
['id', 'source', 'start_t', 'end_t', 'p_ratio']
(0, 'masource1', 0.0, 1.0, 0.5)
(1, 'masource2', 1.0, 2.0, 0.5)
(2, 'masource3', 2.0, 3.0, 0.5)
COUNT = 3
(1, 'masource2', 1.0, 2.0, 0.5)
(0, 'masource1', 0.0, 1.0, 0.5)
SYNCHRONOUS: (2,)
JOURNAL: ('delete',)

In [3]:
import sqlite3
import proxycodelib
from jupytools import mooltipath

DATASET_NAME =  'MAIN1000'

db = sqlite3.connect(mooltipath('datasets', DATASET_NAME, 'dataset.db'))
db.row_factory = sqlite3.Row

c = db.cursor()

print('-------------- SELECT -------------------')
c.execute("SELECT * FROM chunks WHERE id < 10")
rows = c.fetchall()
for item in rows:
    print(dict(item))

print('-------------- COUNT -------------------')   
c.execute("SELECT COUNT(*) FROM CHUNKS WHERE p_ratio < 0.49")    
print(c.fetchone()[0])

connexion.close()

-------------- SELECT -------------------
{'id': 0, 'hive': 'CF001', 'start_t': 0.0, 'end_t': 1.0, 'p_ratio': 0.0}
{'id': 1, 'hive': 'CF001', 'start_t': 1.0, 'end_t': 2.0, 'p_ratio': 0.0}
{'id': 2, 'hive': 'CF001', 'start_t': 2.0, 'end_t': 3.0, 'p_ratio': 0.0}
{'id': 3, 'hive': 'CF001', 'start_t': 3.0, 'end_t': 4.0, 'p_ratio': 0.0}
{'id': 4, 'hive': 'CF001', 'start_t': 4.0, 'end_t': 5.0, 'p_ratio': 0.0}
{'id': 5, 'hive': 'CF001', 'start_t': 5.0, 'end_t': 6.0, 'p_ratio': 0.0}
{'id': 6, 'hive': 'CF001', 'start_t': 6.0, 'end_t': 7.0, 'p_ratio': 0.0}
{'id': 7, 'hive': 'CF001', 'start_t': 7.0, 'end_t': 8.0, 'p_ratio': 0.0}
{'id': 8, 'hive': 'CF001', 'start_t': 8.0, 'end_t': 9.0, 'p_ratio': 0.0}
{'id': 9, 'hive': 'CF001', 'start_t': 9.0, 'end_t': 10.0, 'p_ratio': 0.0}
-------------- COUNT -------------------
17961

In [4]:
import sqlite3
import proxycodelib
from jupytools import mooltipath
import random

random.seed(23081965,2)

DATASET_NAME =  'MAIN1000'

def getRand(n):
    db = sqlite3.connect(mooltipath('datasets', DATASET_NAME, 'dataset.db'))
    c = db.cursor()
    # SELECT * FROM table WHERE id IN (SELECT id FROM table ORDER BY RANDOM() LIMIT x)
    c.execute("SELECT * FROM chunks ORDER BY RANDOM() LIMIT " + str(n))
    results = c.fetchall()
    db.close()
    return results
  
items = getRand(30000)

print(items[1000])

(4110, 'CF003', 71.0, 72.0, 0.0)

In [2]:
import sqlite3

data = (
    {"id" : 0, "source" : "masource1", "start_t" : 0.0, "end_t" : 1.0, "p_ratio" : 0.5},
    {"id" : 1, "source" : "masource2", "start_t" : 1.0, "end_t" : 2.0, "p_ratio" : 0.5},
    {"id" : 2, "source" : "masource3", "start_t" : 2.0, "end_t" : 3.0, "p_ratio" : 0.5}
)

db = sqlite3.connect("tmp/database4.db")

c = db.cursor()
c.execute('''DROP TABLE IF EXISTS A''')
c.execute('''DROP TABLE IF EXISTS B''')
c.execute('''CREATE TABLE A(
    id INTEGER PRIMARY KEY UNIQUE,
    source TEXT,
    start_t REAL,
    end_t REAL,
    p_ratio REAL
)''')

c.execute('''CREATE TABLE B(
    id INTEGER PRIMARY KEY UNIQUE,
    source TEXT,
    start_t REAL,
    end_t REAL,
    p_ratio REAL
)''')

c.executemany("INSERT INTO A (id, source, start_t, end_t, p_ratio) VALUES (:id, :source, :start_t, :end_t, :p_ratio)", data)

c.executemany("INSERT INTO B (id, source, start_t, end_t, p_ratio) VALUES (:id, :source, :start_t, :end_t, :p_ratio)", data[1:2])

print("Count A =", c.execute("SELECT COUNT(*) FROM A").fetchone()[0])

print("Count B =", c.execute("SELECT COUNT(*) FROM B").fetchone()[0])

tname = 'A'
req = f"SELECT COUNT(*) FROM '{tname}' WHERE id = ?"
print(req)
c = db.cursor()
e = c.execute(req, (1,))
print("Count X =", e.fetchone()[0])
c.close()




db.commit()

db.close()

Count A = 3
Count B = 1
SELECT COUNT(*) FROM 'A' WHERE id = ?
Count X = 1

In [ ]:
#exemple of contextlib usage
import sqlite3
import contextlib

# Nice
def query1(statement):
    with contextlib.closing(sqlite3.connect(path_to_file)) as conn: # auto-closes
            # auto-closes ( needed because cursor is not a context manager)
            with contextlib.closing(conn.cursor()) as cursor: 
                cursor.execute(statement)

# Bad
def query2(statement):
    with sqlite3.connect(path_to_file)) as conn: # auto commit only
        with conn: # useless, same as above
            with conn.cursor() as cursor: # does nothing
                cursor.execute(statement)

# bad
def query3(statement):
    with sqlite3.connect(path_to_file)) as conn: # auto commit only
        with conn.cursor() as cursor: # does nothing
            cursor.execute(statement)
        conn.close()    

# Ok
def query5 (statement):
    con = sqlite3.connect(path_to_file)
    with con:
        cur = con.cursor()
        cur.execute(statement)
        res = cur.fetchall()
    if con:
        con.close()

    return res

In [1]:
import kilroy_was_here
import sqlite3
from lib.dblib import DatasetDb

data = (
    {"id" : 0, "source" : "masource1", "start_t" : 0.0, "end_t" : 1.0, "p_ratio" : 0.5},
    {"id" : 1, "source" : "masource2", "start_t" : 1.0, "end_t" : 2.0, "p_ratio" : 0.5},
    {"id" : 2, "source" : "masource3", "start_t" : 2.0, "end_t" : 3.0, "p_ratio" : 0.5}
)

DBPATH = "tmp/database4.db"

db = sqlite3.connect(DBPATH)

c = db.cursor()
c.execute('''DROP TABLE IF EXISTS A''')
c.execute('''DROP TABLE IF EXISTS B''')
c.execute('''CREATE TABLE A(
    id INTEGER PRIMARY KEY UNIQUE,
    source TEXT,
    start_t REAL,
    end_t REAL,
    p_ratio REAL
)''')

c.execute('''CREATE TABLE B(
    id INTEGER PRIMARY KEY UNIQUE,
    source TEXT,
    start_t REAL,
    end_t REAL,
    p_ratio REAL
)''')

c.executemany("INSERT INTO A (id, source, start_t, end_t, p_ratio) VALUES (:id, :source, :start_t, :end_t, :p_ratio)", data)

c.executemany("INSERT INTO B (id, source, start_t, end_t, p_ratio) VALUES (:id, :source, :start_t, :end_t, :p_ratio)", data[1:2])


db.commit()
db.close()

with DatasetDb(DBPATH) as db:
    print(db.getCount('A'))
    print(db.getOneAsList('A'))    
    print(db.getOneAsDict('A')) 
    print("---------------------")
    print(db.getAllAsList('A', "start_t > 0.9 and start_t < 1.1"))  
    print(db.getAllAsList('A', "start_t > ? and start_t < ?", 0.9, 1.1)) 
    print(db.getAllAsDict('A', "start_t > ? and start_t < ?", 0.9, 2.1))

3
(0, 'masource1', 0.0, 1.0, 0.5)
{'id': 0, 'source': 'masource1', 'start_t': 0.0, 'end_t': 1.0, 'p_ratio': 0.5}
---------------------
[(1, 'masource2', 1.0, 2.0, 0.5)]
[(1, 'masource2', 1.0, 2.0, 0.5)]
[{'id': 1, 'source': 'masource2', 'start_t': 1.0, 'end_t': 2.0, 'p_ratio': 0.5}, {'id': 2, 'source': 'masource3', 'start_t': 2.0, 'end_t': 3.0, 'p_ratio': 0.5}]